### ISSUE TITLE
Not all logs being delivered on graceful shutdown.

### ISSUE THREAD

**Issue by iamdevonbutler** [logdna/nodejs#15]
Hey,

I'm using Logdna w/ bunyan. On SIGTERM my logs are being logged to console but don't make it to logdna. I see you have some sort of message buffer. Is there a way to flush it manually or another way to persist the logs to your app?

**Comment by respectus** [comment]
Hi @iamdevonbutler, thanks for keeping up with this module. I've investigated your issue and there is a prototype function called _flush that can be called on the logger instance, which will manually flush your logs. I also added functionality to the module version 1.2.9, which will automatically flush all messages in existing loggers upon detection of SIGINT or SIGTERM. Please let me know if this does not work as expected. Thanks for the feedback it is much appreciated and it's the fastest way for us to improve the product!

**Comment by iamdevonbutler** [comment]
Nice. that's helpful. I still have a use case that isn't covered. 

In scenarios when, let's say, your database connection dies, I want my app to call a shutdown func and manually take itself offline. When I do that, I will need to manually flush the logdna logs, because SIGINT/SIGTERM are never called, but i'm not sure I can as is (the "loggers" closure is not exposed) but I could be wrong tho.

**Comment by respectus** [comment]
I believe if you have a reference to the logger that you instantiate using createLogger you can call the function _flush on that instance and it will manually flush the log buffer. This can be a bit annoying if you have multiple loggers, so I have exposed a flushAll function in version 1.3.0 that flushes all loggers instantiated. Please let me know if you still have any issues with the module, appreciate the feedback!

**Comment by respectus** [comment]
@iamdevonbutler Just wanted to follow up here for a change that will effect your logging setup. I've modified the module so now version 1.3.2 requires that when you instantiate the Logger you pass in the options cleanUpSIGTERM as a boolean set to true, and the option cleanUpSIGINT set to true. Upon SIGINT or SIGTERM the loggers will flush properly and remove references to themselves. We decided it would be best not to have the default behavior be a flush and clean up for every person using the module. It's now an opt-in option and you will have to set the cleanUpSIGTERM and cleanUpSIGINT to true in order to flush logs. The cleanUpAll and flushAll functions that are exposed will allow you to manually clean up even when SIGINT or SIGTERM are not triggered. Please do let me know if you have any issues with this version of the module. Really appreciate your feedback on this, thanks!

**Comment by iamdevonbutler** [comment]
got it thanks.
