### ISSUE TITLE
LogDNA Winston Transport in typescript

### ISSUE THREAD

**Issue by Halt001** [logdna/nodejs#23]
How can one use the LogDNA Winston Transport using Typescript? The line
`winston.add(winston.transports.Logdna, options);`
causes:  _Property 'Logdna' does not exist on type 'Transports'_.

Any help is appreciated.

**Comment by respectus** [comment]
Hi @Halt001,
Thanks for reporting this issue with Typescript. In order to bypass this error, instead of calling `winston.add(winston.transports.Logdna, options);`
using the winston.transports.Logdna object which Typescript isn't able to resolve properly, we can try using the equivalent WinstonTransport object which is exposed in index.js of the logdna module. This is the example configuration I would recommend 
```javascript
var logdna = require('logdna');
var WinstonTransport = logdna.WinstonTransport;
var winston = require('winston');
var options = {
    key: apikey,
    hostname: myHostname,
    ip: ipAddress,
    mac: macAddress,
    app: appName,
    env: envName
};

// Defaults to false, when true ensures meta object will be searchable
options.index_meta = true;

// Only add this line in order to track exceptions
options.handleExceptions = true;

winston.add(WinstonTransport, options);
```

Please do let me know if this solution does not work, we can continue debugging from there. Appreciate you bringing this to our attention!

**Comment by tvhalteren** [comment]
Thanks, that was very helpful. I did use the following syntax to make it work.
 
```
import { WinstonTransport } from 'logdna';
winston.add(WinstonTransport, logDNAOptions);
```

**Comment by Halt001** [comment]
Thanks, that was very helpful. I did use the following syntax to make it work.

```
import { WinstonTransport } from 'logdna';
winston.add(WinstonTransport, logDNAOptions);
```

**Comment by respectus** [comment]
Thanks @Halt001 really do appreciate you sharing the Typescript equivalent to resolve this issue!
