### ISSUE TITLE
Listener Leak

### ISSUE THREAD

**Issue by jontonsoup** [logdna/nodejs#95]
Hi, 

I'm getting a listener leak when I use the logger. I've attached a chrome performance monitor snapshot.

The "ingest" blocks stand for: 

<img width="816" alt="image" src="https://user-images.githubusercontent.com/845636/81439045-c1476100-913b-11ea-8687-d90dde3b7fdc.png">

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/845636/81438853-72013080-913b-11ea-963a-adf528c3e5c7.png">

```import { app, remote } from "electron";
import {ConstructorOptions, createLogger, Logger} from "logdna";
import {hostname} from "os";
import {logDNAKey} from "../settings";
import {env} from "./env";

class LogDNALogger {
    private logger: Logger;
    private user: string;
    constructor() {

        const options: ConstructorOptions = {
            app: "live-data-entry-desktop",
            env: env(),
            hostname: hostname(),
        };

        // @ts-ignore
        options.index_meta = true;
        this.logger = createLogger(logDNAKey, options);
    }

    public log(message: string) {
      this.logger.log(message);
    }
}

export const logger = new LogDNALogger();
```

**Comment by darinspivey** [comment]
Hi @jontonsoup, thanks for showing us your findings!  We are about to release an update to this code that will improve efficiency and clean a few things up (it will be a `major` despite the changes being somewhat minor in nature).  First, a patch release will be going out shortly with 100% test coverage, so that's a good place to start.  After the `major` release, it'd be great if you could re-run your tests to see if the problem still exists.  If so, we'll be happy to investigate.  Stay tuned!

**Comment by jontonsoup** [comment]
thanks! Will do.

**Comment by darinspivey** [comment]
@jontonsoup , our new client has been released. Please refer to the README in our new package, [@logdna/logger](https://www.npmjs.com/package/@logdna/logger), and let us know if you still see leaks.

Feel free to open any issues under that new repository.  Thanks!
